### PR TITLE
More tweaks, thrice

### PR DESCRIPTION
**Pull request by RQWorldblender**
Here are more changes of mine to come. There are some new textures this time:
- A new bucket_cactus texture (.xcf file is attached in case you need to edit it; rename from this .png file: bucket_cactus xcf)
- A texture for the revised soft-touch crystal shovel, which uses sticks instead of steel for its handle (.xcf file is attached in case you need to edit it; rename from this .png file: 
crystal_shovel_soft xcf); the old texture is used for a version of this shovel without soft-touch

In the meantime, there have been some major biome changes in the default game, found at [https://forum.minetest.net/viewtopic.php?f=18&t=15939](url). You might want to consider incorporating some of these new biomes and whatever new items they use into this mod.
I would also like to suggest varying the fuel times for all the tree types introduced by this mod, as the default ones already are, so that gameplay becomes slightly more realistic.

### CODE REVIEW

**Comment by tenplus1** [comment]
New tweaks added, thanks again...  but, foods, crystal shovel, fishing rod and bonemeal are ethereal specific items to be enabled at all times.

**Comment by RQWorldblender** [comment]
Not all of my changes got committed in, but some is better than nothing. :) Anyways, you forgot about the dirt footstep changes again (a commit of mine fixed this again), and also remove the cools_lava properties from the crystal spike and crystal blocks, so that they are more consistent with the stairs and stairsplus counterparts. In the next few updates, I'll have new textures for the dirt ready.

**Comment by tenplus1** [comment]
The dirt footsteps and cool_lava were both added, make sure you are viewing MY github version of ethereal and not your forked version.

**Comment by RQWorldblender** [comment]
I should've went into more detail (this is what I see in your version):
- The dry dirt has the grass footsteps sound, but not the other dirts other than the green dirt. Remove the footstep sound from dry dirt and place it in the function where the other dirts are being registered.
- Crystal spikes and crystal blocks are not consistent with their counterparts in stairs and stairsplus, in the the stairsplus and stairs versions do not have the cools_lava property. It's up to you to decide whether you want the crystals to be able to cool lava or not.

**Comment by tenplus1** [comment]
Gotcha...  Fixed dirt sounds, crystal stairs have lava_cooling and shovel has creative checks...

**Comment by RQWorldblender** [comment]
Good! You're getting there, but I still notice some more things that need to change:
- Dried dirt does not share the same description with its stairs and stairsplus counterparts, where they are named "Dry Dirt ..." instead. Since it's just dirt, it does not need the footstep sound.
- Change the gain sound for the crystal shovel from 0.35 to 0.4 (this is minor, but I'll leave that up to you, but that's what I saw when reading the code from the default game for when digging leaves), and remove "pos = pos" in the sound function, since that causes the sound to be played at the node instead of directly for the player, and if the player digs that node and is quite far from it, the sound will be less audible.

**Comment by RQWorldblender** [comment]
I'm still waiting for you to fix the following things before I continue making more changes to my fork:
-  Dried dirt does not share the same description with its stairs and stairsplus counterparts, where they are named "Dry Dirt ..." instead. Since it's just dirt, it does not need the footstep sound.
- Change the gain sound for the crystal shovel from 0.35 to 0.4 (this is minor, but I'll leave that up to you, but that's what I saw when reading the code from the default game for when digging leaves), and remove "pos = pos" in the sound function, since that causes the sound to be played at the node instead of directly for the player, and if the player digs that node and is quite far from it, the sound will be less audible.

**Comment by tenplus1** [comment]
so wait, you want stairs to be renamed to "dried dirt ..." and the removal of pos=pos in shovel sounds ?

**Comment by RQWorldblender** [comment]
Actually, it's up to you on what you want to do. I'm just trying to bring certain stuff in-live with the latest dev versions of the Minetest Game, but it's up to you whether you want to implement whatever I said.
**But do not forget to remove the footstep sound from dry dirt, at the very least.**

**Comment by tenplus1** [comment]
Okies, dry dirt sound has been fixed as has the stair names...  The pos=pos for crystal shovel will be kept though as sound shoudl come from actual block you dig.

**Comment by RQWorldblender** [comment]
Very good. That's all the changes I will suggest to you for now. If there are more changes of mine to come, they will come in the form of new pull requests.

**Pull request closed without merging**
