### PR TITLE
Update stairs.lua

### PR DESCRIPTION
**Pull request by oliver-geht-dich-nichts-an**
add stairs and slabs from moreblocks if present.

### CODE REVIEW

**Comment by HybridDog** [comment]
l use moreblocks but removed stairsplus from it because l do not like stairsplus, so please use ```minetest.global_exists("stairsplus")``` instead of ```minetest.get_modpath("moreblocks")```.
And to ensure that moreblocks is loaded before ethereal, add ```moreblocks?``` to depends.txt

**Comment by oliver-geht-dich-nichts-an** [comment]
done!!

**Comment by HybridDog** [comment]
thanks

**Comment by HybridDog** [comment]
thanks,
you can btw put the depends updates commit to this PR, just run following
$ wget https://patch-diff.githubusercontent.com/raw/tenplus1/ethereal/pull/18.patch && git am 18.patch && git push

**Comment by oliver-geht-dich-nichts-an** [comment]
Thanks
Am 22.03.2016 10:57 schrieb "HybridDog" <notifications@github.com>:

**Comment by tenplus1** [comment]
Added, thanks for the help :)

**Pull request closed without merging**
