### PR TITLE
Dirt textures and selection box updates

### PR DESCRIPTION
**Pull request by RQWorldblender**
Here are the changes I've made once again so far. The most noticeable changes deal with the dirt textures and selection boxes for things that render like plants. There are also some changes dealing with the saplings, noticeably by adding them to the sapling group.
All of the XCF files I produced can be found in the archive below:
[ethereal-grass-new.zip](https://github.com/tenplus1/ethereal/files/665333/ethereal-grass-new.zip)

There may be more changes coming, but these may make much more drastic changes to your mod and require that I spend more time testing, sometimes with your input:
- Rename the rest of your textures to use standard namespace scheming (the rest of the textures will have "ethereal_" prefixed to them if they do not have it, and become more descriptive instead of using numbers; alias will be created for all this).
- Moretrees compatibility for the bonemeal component and either aliases or recognition of moretrees equivalents.
- Varying digging times and furnace burn times for all of the trees in this mod.
- Adding new decorations from the default game, such as bushes with stems, tree logs, and coral blocks. In return for this, something may need to be done about the bushes and corals from this mod.
- Considering about including some of the new biomes from the default game, such as cold deserts with silver sand, sand with sandstone underneath, and jungle trees growing from underwater, as known as the swamps.

### CODE REVIEW

**Comment by tenplus1** [comment]
Will check out your latest changes... The 'sapling' group isnt required as default abm has no need to check ethereal saplings... Changing texture names will break already made texture packs which support ethereal.

**Comment by RQWorldblender** [comment]
Wait; the list of changes I proposed except the dirt textures and the new selection boxes have not yet been committed. Those are changes that I plan on working on next. However, I knew that on changing the texture names, that some texture packs providing replacement images for this mod would break. Instead of changing the texture names, I think that at least changing the node names would be better, but they will still use the current texture names. Example changes (not yet committed):
- ethereal:coral2 --> ethereal:coral_cyan
- ethereal:coral3 --> ethereal:coral_orange
- ethereal:coral4 --> ethereal:coral_pink
- ethereal:coral5 --> ethereal:coral_green
- ethereal:bush --> ethereal:bamboo_bush (The bush may seem too generic to receive a name change)
- ethereal:bush2 --> ethereal:aspen_bush
- ethereal:bush3 --> ethereal:pine_bush

**Comment by tenplus1** [comment]
Changing the node names would break compatibility with older worlds and alias' would need to be setup for all nodes changed.  Also look at how coral is spawned, the function I made relies on numbered names for simplicity.

**Comment by RQWorldblender** [comment]
I returned to some compatibility; the grass textures (not the side ones) are back to having "_top" appended after the name. By including just the side textures, the visual changes have not yet been completed. I have completed them for you now.

**Comment by RQWorldblender** [comment]
Oh good! I'm seeing many of my suggestions become implemented. But the last thing you might have forgot was to include the new ethereal_grass_*_top textures. Without them, the existing ones may look like that they can repeat, which was why the grass top texture was replaced.

**Pull request closed without merging**
